{"_class": "org.jenkinsci.plugins.workflow.job.WorkflowRun",
    "actions": [
                {"_class": "hudson.model.CauseAction", "causes": [
                    {"_class": "hudson.model.Cause$UserIdCause",
                     "shortDescription": "Started by user manish_singh@in.ibm.com",
                     "userId": "manish_singh@in.ibm.com",
                     "userName": "manish_singh@in.ibm.com"},
                    {"_class": "com.sonyericsson.rebuild.RebuildCause",
                     "shortDescription": "Rebuilds build #8", "upstreamBuild": 8,
                     "upstreamProject": "hci_pipeline_temp",
                     "upstreamUrl": "job/hci_pipeline_temp/"}]},
    {"_class": "hudson.model.ParametersAction",
     "parameters": [
        {"_class": "hudson.model.StringParameterValue",
         "name": "OCP_CONSOLE_URL",
         "value": "https://console-openshift-console.apps.isf-racka.rtp.raleigh.ibm.com"},
        {"_class": "hudson.model.StringParameterValue", "name": "USERNAME",
         "value": "kubeadmin"},
        {"_class": "hudson.model.StringParameterValue", "name": "PASSWORD",
         "value": "i8YSj-oQSpd-S32vU-fIYRRpy"},
        {"_class": "hudson.model.StringParameterValue",
         "name": "ISF_NAMESPACE", "value": "ibm-spectrum-fusion-ns"},
        {"_class": "hudson.model.StringParameterValue", "name": "GIT_BRANCH",
         "value": "master"},
        {"_class": "hudson.model.TextParameterValue", "name": "PARAMS_BVT",
         "value": "Storage_Operator_Bvt\u000aServiceability_Operator_Bvt"},
        {"_class": "hudson.model.TextParameterValue", "name": "PARAMS_FVT_API",
         "value": "ICS_Operator_Bvt"},
        {"_class": "hudson.model.TextParameterValue", "name": "PARAMS_FVT_UI",
         "value": "Network_Operator_Bvt\u000aEvent_Manager_Operator_Bvt"}]},
    {"_class": "jenkins.metrics.impl.TimeInQueueAction",
     "blockedDurationMillis": 0, "blockedTimeMillis": 0,
     "buildableDurationMillis": 0, "buildableTimeMillis": 12419,
     "buildingDurationMillis": 275771, "executingTimeMillis": 255899,
     "executorUtilization": 0.93, "subTaskCount": 1,
     "waitingDurationMillis": 0, "waitingTimeMillis": 0}, {},
    {"_class": "hudson.plugins.git.util.BuildData", "buildsByBranchName": {
        "refs/remotes/origin/xfail_fixes": {
            "_class": "hudson.plugins.git.util.Build", "buildNumber": 9,
            "buildResult": null,
            "marked": {"SHA1": "170e7b6950a66579b467567ff898429ba00b7086",
                       "branch": [
                           {"SHA1": "170e7b6950a66579b467567ff898429ba00b7086",
                            "name": "refs/remotes/origin/xfail_fixes"}]},
            "revision": {"SHA1": "170e7b6950a66579b467567ff898429ba00b7086",
                         "branch": [{
                                        "SHA1": "170e7b6950a66579b467567ff898429ba00b7086",
                                        "name": "refs/remotes/origin/xfail_fixes"}]}},
        "refs/remotes/origin/master": {
            "_class": "hudson.plugins.git.util.Build", "buildNumber": 1,
            "buildResult": null,
            "marked": {"SHA1": "0419701e25a0e1191e8014598845210cb967a7be",
                       "branch": [
                           {"SHA1": "0419701e25a0e1191e8014598845210cb967a7be",
                            "name": "refs/remotes/origin/master"}]},
            "revision": {"SHA1": "0419701e25a0e1191e8014598845210cb967a7be",
                         "branch": [{
                                        "SHA1": "0419701e25a0e1191e8014598845210cb967a7be",
                                        "name": "refs/remotes/origin/master"}]}}},
     "lastBuiltRevision": {"SHA1": "170e7b6950a66579b467567ff898429ba00b7086",
                           "branch": [{
                                          "SHA1": "170e7b6950a66579b467567ff898429ba00b7086",
                                          "name": "refs/remotes/origin/xfail_fixes"}]},
     "remoteUrls": ["https://github.ibm.com/ProjectAbell/Automation.git"],
     "scmName": ""}, {},
    {"_class": "org.jenkinsci.plugins.workflow.libs.LibrariesAction"},
    {"_class": "org.jenkinsci.plugins.workflow.cps.EnvActionImpl"},
    {"_class": "hudson.tasks.junit.TestResultAction", "failCount": 14,
     "skipCount": 0, "totalCount": 14, "urlName": "testReport"}, {}, {}, {},
    {},
    {"_class": "org.jenkinsci.plugins.displayurlapi.actions.RunDisplayAction"},
    {
        "_class": "org.jenkinsci.plugins.pipeline.modeldefinition.actions.RestartDeclarativePipelineAction"},
    {}, {"_class": "org.jenkinsci.plugins.workflow.job.views.FlowGraphAction"},
    {}, {}, {}], "artifacts": [
    {"displayPath": "test_event_manager_operator.log",
     "fileName": "test_event_manager_operator.log",
     "relativePath": "Automation/logs/apis/hci/test_bvt/test_event_manager_operator.log"},
    {"displayPath": "test_ics_operator.log",
     "fileName": "test_ics_operator.log",
     "relativePath": "Automation/logs/apis/hci/test_bvt/test_ics_operator.log"},
    {"displayPath": "test_network_operator.log",
     "fileName": "test_network_operator.log",
     "relativePath": "Automation/logs/apis/hci/test_bvt/test_network_operator.log"},
    {"displayPath": "test_serviceability_operator.log",
     "fileName": "test_serviceability_operator.log",
     "relativePath": "Automation/logs/apis/hci/test_bvt/test_serviceability_operator.log"},
    {"displayPath": "test_storage_operator.log",
     "fileName": "test_storage_operator.log",
     "relativePath": "Automation/logs/apis/hci/test_bvt/test_storage_operator.log"}],
 "building": false, "description": null, "displayName": "#9_BVT",
 "duration": 275771, "estimatedDuration": 229224, "executor": null,
 "fullDisplayName": "hci_pipeline_temp #9_BVT", "id": "9", "keepLog": false,
 "number": 9, "queueId": 10990, "result": "UNSTABLE",
 "timestamp": 1642930188582,
 "url": "https://sys-abell-team-jenkins.swg-devops.com/job/hci_pipeline_temp/9/",
 "changeSets": [], "culprits": [{
                                    "absoluteUrl": "https://sys-abell-team-jenkins.swg-devops.com/user/manish_singh",
                                    "fullName": "manish_singh"}],
 "nextBuild": {"number": 10,
               "url": "https://sys-abell-team-jenkins.swg-devops.com/job/hci_pipeline_temp/10/"},
 "previousBuild": {"number": 8,
                   "url": "https://sys-abell-team-jenkins.swg-devops.com/job/hci_pipeline_temp/8/"}}
